# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
orbs:
  wp-product-orb: wpengine/wp-product-orb@1.3.0
  php: circleci/php@1.1.0

jobs:
  checkout:
    executor: wp-product-orb/default
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  plugin-wpe-headless-checkout:
    executor: wp-product-orb/default
    working_directory: ~/project/plugins/wpe-headless
    environment:
      WPE_SESSION_DIR: ./.wpe
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Make artifacts build directory
          command: |
            [ ! -d "build" ] && mkdir build &>/dev/null
      - wp-product-orb/get-version-from-php:
          filename: wpe-headless.php
          return_var: BUILD_VERSION
      - wp-product-orb/variable:
          var: BUILD_VERSION
          value: $BUILD_VERSION
      - persist_to_workspace:
          root: ~/project
          paths:
            - plugins/wpe-headless

  plugin-wpe-headless-composer:
    executor: php/default
    working_directory: ~/project/plugins/wpe-headless
    steps:
      - attach_workspace:
          at: ~/project
      - php/install-composer
      - php/install-packages:
          app-dir: .
      - run:
          name: Composer PHP lint and code sniffer
          command: |
            /usr/local/bin/composer lint && /usr/local/bin/composer phpcs
          working_directory: .
      - persist_to_workspace:
          root: ~/project
          paths:
            - plugins/wpe-headless

  plugin-wpe-headless-bundle-zip:
    executor: wp-product-orb/default
    working_directory: ~/project/plugins/wpe-headless
    environment:
      WPE_SESSION_DIR: ./.wpe
    steps:
      - attach_workspace:
          at: ~/project
      - wp-product-orb/variable-load
      - run:
          name: "Bundle plugin files into a zip"
          command: |
            cd ..
            zip --verbose -x@wpe-headless/.zipignore -x *.wpe/* */build/ -r "wpe-headless/build/wpe-headless.$BUILD_VERSION.zip" wpe-headless
      - store_artifacts:
          path: build
      - persist_to_workspace:
          root: ~/project
          paths:
            - plugins/wpe-headless/build

  plugin-wpe-headless-bundle-json:
    executor: wp-product-orb/parser
    working_directory: ~/project/plugins/wpe-headless
    environment:
      WPE_SESSION_DIR: ./.wpe
    steps:
      - attach_workspace:
          at: ~/project
      - wp-product-orb/variable-load
      - wp-product-orb/parse-wp-readme:
          infile: readme.txt
          outfile: build/wpe-headless.$BUILD_VERSION.json
      - store_artifacts:
          path: build
      - persist_to_workspace:
          root: ~/project
          paths:
            - plugins/wpe-headless/build

  plugin-wpe-headless-deploy:
    executor: wp-product-orb/authenticate
    working_directory: ~/project/plugins/wpe-headless
    environment:
      WPE_SESSION_DIR: ./.wpe
    parameters:
      auth_url:
        type: string
      upload_url:
        type: string
    steps:
      - attach_workspace:
          at: ~/project
      - wp-product-orb/variable-load
      - wp-product-orb/authenticate:
          user: WPE_LDAP_USER
          pass: WPE_LDAP_PASS
          url: << parameters.auth_url >>
      - wp-product-orb/post-zip:
          url: << parameters.upload_url >>/wpe-headless
          zip: build/wpe-headless.$BUILD_VERSION.zip
          json: build/wpe-headless.$BUILD_VERSION.json
          version: $BUILD_VERSION

workflows:
  version: 2

  # Workflows defined for each package.
  # tag example for deploying an update for wpe-headless: plugin/wpe-headless/1.0.0
  plugin-wpe-headless:
    jobs:
      - checkout
      - plugin-wpe-headless-checkout:
          requires:
            - checkout
      - plugin-wpe-headless-composer:
          requires:
            - plugin-wpe-headless-checkout
      - plugin-wpe-headless-bundle-zip:
          requires:
            - plugin-wpe-headless-checkout
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^plugin-test\/wpe-headless\/\S+/
      - plugin-wpe-headless-bundle-json:
          requires:
            - plugin-wpe-headless-checkout
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^plugin-test\/wpe-headless\/\S+/
      - plugin-wpe-headless-deploy:
          name: "Deploy zip to api (staging)"
          requires:
            - plugin-wpe-headless-bundle-zip
            - plugin-wpe-headless-bundle-json
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^plugin-test\/wpe-headless\/\S+/
          context: wpe-ldap-creds
          auth_url: https://auth-staging.wpengine.io/v1/tokens
          upload_url: https://wp-product-info-staging.wpesvc.net/v1/plugins
      - plugin-wpe-headless-deploy:
          name: "Deploy zip to api (production)"
          requires:
            - plugin-wpe-headless-bundle-zip
            - plugin-wpe-headless-bundle-json
          filters:
            branches:
              ignore: /.*/
            tags:
              # tag ex. plugin/wpe-headless/1.0.0
              only: /^plugin-test\/wpe-headless\/\S+/
          context: wpe-ldap-creds
          auth_url: https://auth.wpengine.io/v1/tokens
          upload_url: https://wp-product-info.wpesvc.net/v1/plugins
