name: Test Packages
on: pull_request
jobs:
  test_packages:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        version: [14, 16, 18]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - run: rm package-lock.json
      - run: npm install --loglevel silly
      - run: npm run build --loglevel silly
      - run: npm test
        continue-on-error: FALSE
